### ISSUE TITLE
which tensorflow and keras version shall we use? 

### ISSUE THREAD

**Issue by liaosiyang** [morimoris/keras_VESPCN#1]
hello, I run the code in

tensorflow-gpu 1.14.0
keras 2.2.4

but found this question:

ValueError: Graph disconnected: cannot obtain value for tensor Tensor("lambda_2/DepthToSpace:0", shape=(?, ?, ?, 2), dtype=float32) at layer "concatenate_2". The following previous layers were accessed without issue: ['input_t', 'input_t_plus_1', 'input_t_minus_1']

**Comment by morimoris** [comment]
Thank you for your message.
This is my mistake, I didn't mention it, but 

tensorflow-gpu 2.4.0

is the version.

So, I think the environment is not working with version 1.

**Comment by liaosiyang** [comment]
It worked, thank you very much!
